name: Vuepress Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm install yarn
          yarn
          yarn docs:build
          echo www.sigure.xyz > docs/.vuepress/dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: SigureMo/SigureMo.github.io
          BRANCH: master
          FOLDER: docs/.vuepress/dist
