name: Vuepress Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: git-lfs
        run: |
          git lfs install
          git lfs pull
      - name: git-submodule
        run: |
          git submodule init
          git submodule update
      - uses: actions/setup-node@master
      - name: deploy
        run: |
          npm install yarn
          yarn
          yarn deploy $ACCESS_TOKEN
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
